---
title: "Reproducible Research: Peer Assessment 1"
author: "Pruthvi Raj Venkatesh"
date: "12 February 2019"
output: html_document
---

```{r Setup, include=TRUE}
library(dplyr)
library(lubridate)
library(ggplot2)
knitr::opts_chunk$set(echo = TRUE)

m2h <- function(x=670.93) { 
   h <- floor(x/60) 
   m <- floor(x - h*60) 
   sprintf("%0.2d:%0.2d:00", h, m) 
}

```

## Loading and preprocessing the data
```{r LoadData, include=TRUE}

#Loading Data into a data frame

df <- read.csv("repdata_data_activity/activity.csv")

#Process/transform the data

df <- cbind(df,setNames(lapply(df[3], m2h),c("Hours")))

df <- cbind(df, as.POSIXct(paste(df$date,df$Hours), format = "%Y-%m-%d %H:%M:%S"))

colnames(df)[5] = "LogDateTime"

dfNonNA <- na.omit(df)
```
## What is mean total number of steps taken per day?

```{r Find Mean, include=TRUE}

# Calculate the total number of steps taken per day

dfStepsPerDay <- setNames(aggregate(df$steps ~ df$date, df, sum), c("Date","StepsPerDay"))

head(dfStepsPerDay)

# Histogram of the total number of steps taken each day

hist(dfStepsPerDay$StepsPerDay, 
     main="Histogram for Steps Taken", 
     xlab="Steps Taken", 
     col="green")

# Calculate and report the mean and median of the total number of steps taken per day

summary(dfStepsPerDay$StepsPerDay)
```

## What is the average daily activity pattern?

```{r Daily Activity, include=TRUE}
#Calculating Avg Per Interval
dfStepsPerInterval <- setNames(aggregate(df$steps ~ df$interval, df, mean), c("interval","AvgSteps"))
#Plotting Per Interval graph
ggplot(dfStepsPerInterval, aes(x = interval, y=AvgSteps)) + labs(title = "Sum of Steps by Interval", x = "interval", y = "steps") + geom_line(color="red")

#Which 5-minute interval, on average across all the days in the dataset, contains the maximum number of steps

maxStepsinInterval <- dfStepsPerInterval[which.max(dfStepsPerInterval$AvgSteps),]

maxStepsinInterval

```

## Imputing missing values

```{r Imputing missing values, include=TRUE}

#Calculate and report the total number of missing values in the dataset (i.e. the total number of rows with NA

nrow(df) - nrow(dfNonNA)

#Devise a strategy for filling in all of the missing values in the dataset. The strategy does not need to be sophisticated. For example, you could use the mean/median for that day, or the mean for that 5-minute interval, etc.

#Merged based on Avg Interval

dfFilled <- merge(df,dfStepsPerInterval)


#Create a new dataset that is equal to the original dataset but with the missing data filled in.

dfFilled$steps[is.na(dfFilled$steps)] <- dfFilled$AvgSteps[is.na(dfFilled$steps)]


#Make a histogram of the total number of steps taken each day and Calculate and report the mean and median total number of steps taken per day. Do these values differ from the estimates from the first part of the assignment? What is the impact of imputing missing data on the estimates of the total daily number of steps?

dfFilledStepsPerDay <- setNames(aggregate(dfFilled$steps ~ dfFilled$date, dfFilled, sum), c("Date","StepsPerDay"))

head(dfFilledStepsPerDay)

# Histogram of the total number of steps taken each day

hist(dfFilledStepsPerDay$StepsPerDay, 
     main="Histogram for Steps Taken", 
     xlab="Steps Taken", 
     col="green")

# Calculate and report the mean and median of the total number of steps taken per day

summary(dfFilledStepsPerDay$StepsPerDay)


```

## Are there differences in activity patterns between weekdays and weekends?

```{r Week End Activity, include=TRUE}
dfFilled$dayofweek <- weekdays(as.Date(dfFilled$date))
dfFilled$weekend <- as.factor(dfFilled$dayofweek=="Saturday"|dfFilled$dayofweek=="Sunday")
levels(dfFilled$weekend) <- c("Weekday", "Weekend")

dfFilledweekday <- dfFilled[dfFilled$weekend=="Weekday",]
dfFilledweekend <- dfFilled[dfFilled$weekend=="Weekend",]

act.int.weekday <- group_by(dfFilledweekday, interval)
act.int.weekday <- summarize(act.int.weekday, steps=mean(steps))
act.int.weekday$weekend <- "Weekday"
act.int.weekend <- group_by(dfFilledweekend, interval)
act.int.weekend <- summarize(act.int.weekend, steps=mean(steps))
act.int.weekend$weekend <- "Weekend"

act.int <- rbind(act.int.weekday, act.int.weekend)
act.int$weekend <- as.factor(act.int$weekend)
ggplot(act.int, aes(interval, steps)) + geom_line() + facet_grid(weekend ~ .)
```
